from dustdevol.BEDE2 import (
    sfr_from_efficiency,
    bursty_sfr_from_efficiency,
    BEDE_inflow,
    Nelson_outflow,
    THEMIS_grain_growth,
    THEMIS_dust_destruction,
    stellar_ejecta,
    BEDE_recycling,
)
from dustdevol.generic import (
    fp,
    fp_array,
    fp_zeros,
    stellar_lifetimes,
    TF01,
    vdHG97_M92_yields,
    vdHG97_M92_cutoffs,
    LN2018_yields,
    LN2018_cutoffs,
    S2020,
)
from dustdevol.imf import salp
from copy import deepcopy

reference = {
    "time_start": fp(0),
    "time_end": fp(13.8),
    "sfr_model": bursty_sfr_from_efficiency,
    "imf": salp,
    "inflow_model": BEDE_inflow,
    "outflow_model": Nelson_outflow,
    "recycling_model": BEDE_recycling,
    "grain_growth_model": THEMIS_grain_growth,
    "destruction_model": THEMIS_dust_destruction,
    "ejecta_model": stellar_ejecta,
    "init_gas": fp_array([0.5e10]),
    "init_star": fp_array([0]),
    "init_metal": fp_array([0, 0]),
    "init_dust": fp_array([0]),
    "model_params": {
        "star_formation_efficiency": fp(1),
        "total_inflow": fp(0.5e10),
        "infall_time": fp(2),
        "tot_infall_time": fp(13.79),
        "inflow_metal": fp(0),
        "inflow_dust": fp(0),
        "outflow_metal": fp(1),
        "outflow_dust": fp(1),
        "recycling_scaling": fp(1),
        "IGM_loss": fp(0.2),
        "grain_growth_epsilon_diffuse": fp(5),
        "grain_growth_epsilon_cloud": fp(4000),
        "available_metals": fp(0.2),
        "cold_fraction": fp(0.5),
        "sn_dust_reduction": fp(5),
        "sn_destruction": fp(15),
        "type_Ia_ratio": fp(0),
        "photofrag_efficiency": fp(0.05),
        "silicate_fraction": fp(0.1),
        "stellar_lifetimes": stellar_lifetimes,
        "dust_yields": TF01,
        "metal_yields": vdHG97_M92_yields,
        "yield_table_z_cutoffs": vdHG97_M92_cutoffs,
        "type_Ia_dust_yields": fp_zeros((2, 2)),
        "type_Ia_metal_yields": LN2018_yields,
        "type_Ia_yield_table_z_cutoffs": LN2018_cutoffs,
        "type_Ia_delays": S2020,
        "type_Ia_probability": 0,
    },
    "absolute_tolerance": 1,
    "relative_tolerance": 1e-3,
}

reference_Ia = deepcopy(reference)
reference_Ia["model_params"]["type_Ia_probability"] = 1e-3
